### ISSUE TITLE
添加链接 /. Add links to blog.

### ISSUE THREAD

**Issue by FreeXMelody** [FreeXMelody/FreeXMelody.github.io#3]
### 添加链接格式 /. Format ：
注意后面有一个空格。 Notice there is a blank behind the string.
- class_name: 友链(default) / 有趣的站点 / 开发参考文档 / 常用工具 / 设计素材 / 解决方案站点
- name: “站点名称”
- link: “站点链接”
- avatar: “站点图标”
- descr: “站点描述”
---
### 例 /. Example ：
```yml
class_name: 有趣的站点
name: Youtube
link: https://www.youtube.com/
avatar: https://i.loli.net/2020/05/14/9ZkGg8v3azHJfM1.png
descr: 视频网站 - video website
```
